# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: collector.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import poplar_pb2 as poplar__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='collector.proto',
  package='poplar',
  syntax='proto3',
  serialized_options=_b('Z\010internal'),
  serialized_pb=_b('\n\x0f\x63ollector.proto\x12\x06poplar\x1a\x0cpoplar.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\xda\x01\n\x0c\x45ventMetrics\x12\x0c\n\x04name\x18\x01 \x01(\t\x12(\n\x04time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\n\n\x02id\x18\x03 \x01(\x03\x12.\n\x08\x63ounters\x18\x04 \x01(\x0b\x32\x1c.poplar.EventMetricsCounters\x12*\n\x06timers\x18\x05 \x01(\x0b\x32\x1a.poplar.EventMetricsTimers\x12*\n\x06gauges\x18\x06 \x01(\x0b\x32\x1a.poplar.EventMetricsGauges\"Q\n\x14\x45ventMetricsCounters\x12\x0e\n\x06number\x18\x01 \x01(\x03\x12\x0b\n\x03ops\x18\x02 \x01(\x03\x12\x0c\n\x04size\x18\x03 \x01(\x03\x12\x0e\n\x06\x65rrors\x18\x04 \x01(\x03\"k\n\x12\x45ventMetricsTimers\x12(\n\x05total\x18\x01 \x01(\x0b\x32\x19.google.protobuf.Duration\x12+\n\x08\x64uration\x18\x02 \x01(\x0b\x32\x19.google.protobuf.Duration\"D\n\x12\x45ventMetricsGauges\x12\r\n\x05state\x18\x01 \x01(\x03\x12\x0f\n\x07workers\x18\x02 \x01(\x03\x12\x0e\n\x06\x66\x61iled\x18\x03 \x01(\x08\x32\x8f\x02\n\x14PoplarEventCollector\x12@\n\x0f\x43reateCollector\x12\x15.poplar.CreateOptions\x1a\x16.poplar.PoplarResponse\x12\x39\n\tSendEvent\x12\x14.poplar.EventMetrics\x1a\x16.poplar.PoplarResponse\x12>\n\x0cStreamEvents\x12\x14.poplar.EventMetrics\x1a\x16.poplar.PoplarResponse(\x01\x12:\n\x0e\x43loseCollector\x12\x10.poplar.PoplarID\x1a\x16.poplar.PoplarResponseB\nZ\x08internalb\x06proto3')
  ,
  dependencies=[poplar__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,google_dot_protobuf_dot_duration__pb2.DESCRIPTOR,])




_EVENTMETRICS = _descriptor.Descriptor(
  name='EventMetrics',
  full_name='poplar.EventMetrics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='poplar.EventMetrics.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='poplar.EventMetrics.time', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='poplar.EventMetrics.id', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='counters', full_name='poplar.EventMetrics.counters', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timers', full_name='poplar.EventMetrics.timers', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gauges', full_name='poplar.EventMetrics.gauges', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=325,
)


_EVENTMETRICSCOUNTERS = _descriptor.Descriptor(
  name='EventMetricsCounters',
  full_name='poplar.EventMetricsCounters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='poplar.EventMetricsCounters.number', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ops', full_name='poplar.EventMetricsCounters.ops', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='size', full_name='poplar.EventMetricsCounters.size', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='errors', full_name='poplar.EventMetricsCounters.errors', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=327,
  serialized_end=408,
)


_EVENTMETRICSTIMERS = _descriptor.Descriptor(
  name='EventMetricsTimers',
  full_name='poplar.EventMetricsTimers',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='total', full_name='poplar.EventMetricsTimers.total', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='duration', full_name='poplar.EventMetricsTimers.duration', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=410,
  serialized_end=517,
)


_EVENTMETRICSGAUGES = _descriptor.Descriptor(
  name='EventMetricsGauges',
  full_name='poplar.EventMetricsGauges',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='poplar.EventMetricsGauges.state', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='workers', full_name='poplar.EventMetricsGauges.workers', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='failed', full_name='poplar.EventMetricsGauges.failed', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=519,
  serialized_end=587,
)

_EVENTMETRICS.fields_by_name['time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_EVENTMETRICS.fields_by_name['counters'].message_type = _EVENTMETRICSCOUNTERS
_EVENTMETRICS.fields_by_name['timers'].message_type = _EVENTMETRICSTIMERS
_EVENTMETRICS.fields_by_name['gauges'].message_type = _EVENTMETRICSGAUGES
_EVENTMETRICSTIMERS.fields_by_name['total'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
_EVENTMETRICSTIMERS.fields_by_name['duration'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
DESCRIPTOR.message_types_by_name['EventMetrics'] = _EVENTMETRICS
DESCRIPTOR.message_types_by_name['EventMetricsCounters'] = _EVENTMETRICSCOUNTERS
DESCRIPTOR.message_types_by_name['EventMetricsTimers'] = _EVENTMETRICSTIMERS
DESCRIPTOR.message_types_by_name['EventMetricsGauges'] = _EVENTMETRICSGAUGES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EventMetrics = _reflection.GeneratedProtocolMessageType('EventMetrics', (_message.Message,), {
  'DESCRIPTOR' : _EVENTMETRICS,
  '__module__' : 'collector_pb2'
  # @@protoc_insertion_point(class_scope:poplar.EventMetrics)
  })
_sym_db.RegisterMessage(EventMetrics)

EventMetricsCounters = _reflection.GeneratedProtocolMessageType('EventMetricsCounters', (_message.Message,), {
  'DESCRIPTOR' : _EVENTMETRICSCOUNTERS,
  '__module__' : 'collector_pb2'
  # @@protoc_insertion_point(class_scope:poplar.EventMetricsCounters)
  })
_sym_db.RegisterMessage(EventMetricsCounters)

EventMetricsTimers = _reflection.GeneratedProtocolMessageType('EventMetricsTimers', (_message.Message,), {
  'DESCRIPTOR' : _EVENTMETRICSTIMERS,
  '__module__' : 'collector_pb2'
  # @@protoc_insertion_point(class_scope:poplar.EventMetricsTimers)
  })
_sym_db.RegisterMessage(EventMetricsTimers)

EventMetricsGauges = _reflection.GeneratedProtocolMessageType('EventMetricsGauges', (_message.Message,), {
  'DESCRIPTOR' : _EVENTMETRICSGAUGES,
  '__module__' : 'collector_pb2'
  # @@protoc_insertion_point(class_scope:poplar.EventMetricsGauges)
  })
_sym_db.RegisterMessage(EventMetricsGauges)


DESCRIPTOR._options = None

_POPLAREVENTCOLLECTOR = _descriptor.ServiceDescriptor(
  name='PoplarEventCollector',
  full_name='poplar.PoplarEventCollector',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=590,
  serialized_end=861,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateCollector',
    full_name='poplar.PoplarEventCollector.CreateCollector',
    index=0,
    containing_service=None,
    input_type=poplar__pb2._CREATEOPTIONS,
    output_type=poplar__pb2._POPLARRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendEvent',
    full_name='poplar.PoplarEventCollector.SendEvent',
    index=1,
    containing_service=None,
    input_type=_EVENTMETRICS,
    output_type=poplar__pb2._POPLARRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StreamEvents',
    full_name='poplar.PoplarEventCollector.StreamEvents',
    index=2,
    containing_service=None,
    input_type=_EVENTMETRICS,
    output_type=poplar__pb2._POPLARRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CloseCollector',
    full_name='poplar.PoplarEventCollector.CloseCollector',
    index=3,
    containing_service=None,
    input_type=poplar__pb2._POPLARID,
    output_type=poplar__pb2._POPLARRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_POPLAREVENTCOLLECTOR)

DESCRIPTOR.services_by_name['PoplarEventCollector'] = _POPLAREVENTCOLLECTOR

# @@protoc_insertion_point(module_scope)
