# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metrics.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import poplar_pb2 as poplar__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='metrics.proto',
  package='poplar',
  syntax='proto3',
  serialized_options=_b('Z\010internal'),
  serialized_pb=_b('\n\rmetrics.proto\x12\x06poplar\x1a\x0cpoplar.proto\"\xe9\x01\n\x0fIntervalSummary\x12\x11\n\tcollector\x18\x01 \x01(\t\x12(\n\x06number\x18\x02 \x01(\x0b\x32\x16.poplar.SummaryIntegerH\x00\x12\x34\n\rnumber_values\x18\x03 \x01(\x0b\x32\x1b.poplar.SummaryIntegerSliceH\x00\x12&\n\x05point\x18\x04 \x01(\x0b\x32\x15.poplar.SummaryDoubleH\x00\x12\x32\n\x0cpoint_values\x18\x05 \x01(\x0b\x32\x1a.poplar.SummaryDoubleSliceH\x00\x42\x07\n\x05value\"2\n\x13SummaryIntegerSlice\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x03(\x03\"-\n\x0eSummaryInteger\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x03\"1\n\x12SummaryDoubleSlice\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x03(\x01\",\n\rSummaryDouble\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\x32\xc0\x02\n\x16PoplarMetricsCollector\x12@\n\x0f\x43reateCollector\x12\x15.poplar.CreateOptions\x1a\x16.poplar.PoplarResponse\x12:\n\x0e\x43loseCollector\x12\x10.poplar.PoplarID\x1a\x16.poplar.PoplarResponse\x12\x37\n\x0bResetSample\x12\x10.poplar.PoplarID\x1a\x16.poplar.PoplarResponse\x12\x37\n\x0b\x46lushSample\x12\x10.poplar.PoplarID\x1a\x16.poplar.PoplarResponse\x12\x36\n\x03\x41\x64\x64\x12\x17.poplar.IntervalSummary\x1a\x16.poplar.PoplarResponseB\nZ\x08internalb\x06proto3')
  ,
  dependencies=[poplar__pb2.DESCRIPTOR,])




_INTERVALSUMMARY = _descriptor.Descriptor(
  name='IntervalSummary',
  full_name='poplar.IntervalSummary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='collector', full_name='poplar.IntervalSummary.collector', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='number', full_name='poplar.IntervalSummary.number', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='number_values', full_name='poplar.IntervalSummary.number_values', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='point', full_name='poplar.IntervalSummary.point', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='point_values', full_name='poplar.IntervalSummary.point_values', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='value', full_name='poplar.IntervalSummary.value',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=40,
  serialized_end=273,
)


_SUMMARYINTEGERSLICE = _descriptor.Descriptor(
  name='SummaryIntegerSlice',
  full_name='poplar.SummaryIntegerSlice',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='poplar.SummaryIntegerSlice.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='poplar.SummaryIntegerSlice.value', index=1,
      number=2, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=275,
  serialized_end=325,
)


_SUMMARYINTEGER = _descriptor.Descriptor(
  name='SummaryInteger',
  full_name='poplar.SummaryInteger',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='poplar.SummaryInteger.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='poplar.SummaryInteger.value', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=327,
  serialized_end=372,
)


_SUMMARYDOUBLESLICE = _descriptor.Descriptor(
  name='SummaryDoubleSlice',
  full_name='poplar.SummaryDoubleSlice',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='poplar.SummaryDoubleSlice.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='poplar.SummaryDoubleSlice.value', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=374,
  serialized_end=423,
)


_SUMMARYDOUBLE = _descriptor.Descriptor(
  name='SummaryDouble',
  full_name='poplar.SummaryDouble',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='poplar.SummaryDouble.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='poplar.SummaryDouble.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=425,
  serialized_end=469,
)

_INTERVALSUMMARY.fields_by_name['number'].message_type = _SUMMARYINTEGER
_INTERVALSUMMARY.fields_by_name['number_values'].message_type = _SUMMARYINTEGERSLICE
_INTERVALSUMMARY.fields_by_name['point'].message_type = _SUMMARYDOUBLE
_INTERVALSUMMARY.fields_by_name['point_values'].message_type = _SUMMARYDOUBLESLICE
_INTERVALSUMMARY.oneofs_by_name['value'].fields.append(
  _INTERVALSUMMARY.fields_by_name['number'])
_INTERVALSUMMARY.fields_by_name['number'].containing_oneof = _INTERVALSUMMARY.oneofs_by_name['value']
_INTERVALSUMMARY.oneofs_by_name['value'].fields.append(
  _INTERVALSUMMARY.fields_by_name['number_values'])
_INTERVALSUMMARY.fields_by_name['number_values'].containing_oneof = _INTERVALSUMMARY.oneofs_by_name['value']
_INTERVALSUMMARY.oneofs_by_name['value'].fields.append(
  _INTERVALSUMMARY.fields_by_name['point'])
_INTERVALSUMMARY.fields_by_name['point'].containing_oneof = _INTERVALSUMMARY.oneofs_by_name['value']
_INTERVALSUMMARY.oneofs_by_name['value'].fields.append(
  _INTERVALSUMMARY.fields_by_name['point_values'])
_INTERVALSUMMARY.fields_by_name['point_values'].containing_oneof = _INTERVALSUMMARY.oneofs_by_name['value']
DESCRIPTOR.message_types_by_name['IntervalSummary'] = _INTERVALSUMMARY
DESCRIPTOR.message_types_by_name['SummaryIntegerSlice'] = _SUMMARYINTEGERSLICE
DESCRIPTOR.message_types_by_name['SummaryInteger'] = _SUMMARYINTEGER
DESCRIPTOR.message_types_by_name['SummaryDoubleSlice'] = _SUMMARYDOUBLESLICE
DESCRIPTOR.message_types_by_name['SummaryDouble'] = _SUMMARYDOUBLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IntervalSummary = _reflection.GeneratedProtocolMessageType('IntervalSummary', (_message.Message,), {
  'DESCRIPTOR' : _INTERVALSUMMARY,
  '__module__' : 'metrics_pb2'
  # @@protoc_insertion_point(class_scope:poplar.IntervalSummary)
  })
_sym_db.RegisterMessage(IntervalSummary)

SummaryIntegerSlice = _reflection.GeneratedProtocolMessageType('SummaryIntegerSlice', (_message.Message,), {
  'DESCRIPTOR' : _SUMMARYINTEGERSLICE,
  '__module__' : 'metrics_pb2'
  # @@protoc_insertion_point(class_scope:poplar.SummaryIntegerSlice)
  })
_sym_db.RegisterMessage(SummaryIntegerSlice)

SummaryInteger = _reflection.GeneratedProtocolMessageType('SummaryInteger', (_message.Message,), {
  'DESCRIPTOR' : _SUMMARYINTEGER,
  '__module__' : 'metrics_pb2'
  # @@protoc_insertion_point(class_scope:poplar.SummaryInteger)
  })
_sym_db.RegisterMessage(SummaryInteger)

SummaryDoubleSlice = _reflection.GeneratedProtocolMessageType('SummaryDoubleSlice', (_message.Message,), {
  'DESCRIPTOR' : _SUMMARYDOUBLESLICE,
  '__module__' : 'metrics_pb2'
  # @@protoc_insertion_point(class_scope:poplar.SummaryDoubleSlice)
  })
_sym_db.RegisterMessage(SummaryDoubleSlice)

SummaryDouble = _reflection.GeneratedProtocolMessageType('SummaryDouble', (_message.Message,), {
  'DESCRIPTOR' : _SUMMARYDOUBLE,
  '__module__' : 'metrics_pb2'
  # @@protoc_insertion_point(class_scope:poplar.SummaryDouble)
  })
_sym_db.RegisterMessage(SummaryDouble)


DESCRIPTOR._options = None

_POPLARMETRICSCOLLECTOR = _descriptor.ServiceDescriptor(
  name='PoplarMetricsCollector',
  full_name='poplar.PoplarMetricsCollector',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=472,
  serialized_end=792,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateCollector',
    full_name='poplar.PoplarMetricsCollector.CreateCollector',
    index=0,
    containing_service=None,
    input_type=poplar__pb2._CREATEOPTIONS,
    output_type=poplar__pb2._POPLARRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CloseCollector',
    full_name='poplar.PoplarMetricsCollector.CloseCollector',
    index=1,
    containing_service=None,
    input_type=poplar__pb2._POPLARID,
    output_type=poplar__pb2._POPLARRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ResetSample',
    full_name='poplar.PoplarMetricsCollector.ResetSample',
    index=2,
    containing_service=None,
    input_type=poplar__pb2._POPLARID,
    output_type=poplar__pb2._POPLARRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='FlushSample',
    full_name='poplar.PoplarMetricsCollector.FlushSample',
    index=3,
    containing_service=None,
    input_type=poplar__pb2._POPLARID,
    output_type=poplar__pb2._POPLARRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Add',
    full_name='poplar.PoplarMetricsCollector.Add',
    index=4,
    containing_service=None,
    input_type=_INTERVALSUMMARY,
    output_type=poplar__pb2._POPLARRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_POPLARMETRICSCOLLECTOR)

DESCRIPTOR.services_by_name['PoplarMetricsCollector'] = _POPLARMETRICSCOLLECTOR

# @@protoc_insertion_point(module_scope)
