# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import metrics_pb2 as metrics__pb2
import poplar_pb2 as poplar__pb2


class PoplarMetricsCollectorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateCollector = channel.unary_unary(
        '/poplar.PoplarMetricsCollector/CreateCollector',
        request_serializer=poplar__pb2.CreateOptions.SerializeToString,
        response_deserializer=poplar__pb2.PoplarResponse.FromString,
        )
    self.CloseCollector = channel.unary_unary(
        '/poplar.PoplarMetricsCollector/CloseCollector',
        request_serializer=poplar__pb2.PoplarID.SerializeToString,
        response_deserializer=poplar__pb2.PoplarResponse.FromString,
        )
    self.ResetSample = channel.unary_unary(
        '/poplar.PoplarMetricsCollector/ResetSample',
        request_serializer=poplar__pb2.PoplarID.SerializeToString,
        response_deserializer=poplar__pb2.PoplarResponse.FromString,
        )
    self.FlushSample = channel.unary_unary(
        '/poplar.PoplarMetricsCollector/FlushSample',
        request_serializer=poplar__pb2.PoplarID.SerializeToString,
        response_deserializer=poplar__pb2.PoplarResponse.FromString,
        )
    self.Add = channel.unary_unary(
        '/poplar.PoplarMetricsCollector/Add',
        request_serializer=metrics__pb2.IntervalSummary.SerializeToString,
        response_deserializer=poplar__pb2.PoplarResponse.FromString,
        )


class PoplarMetricsCollectorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateCollector(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CloseCollector(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ResetSample(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FlushSample(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Add(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PoplarMetricsCollectorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateCollector': grpc.unary_unary_rpc_method_handler(
          servicer.CreateCollector,
          request_deserializer=poplar__pb2.CreateOptions.FromString,
          response_serializer=poplar__pb2.PoplarResponse.SerializeToString,
      ),
      'CloseCollector': grpc.unary_unary_rpc_method_handler(
          servicer.CloseCollector,
          request_deserializer=poplar__pb2.PoplarID.FromString,
          response_serializer=poplar__pb2.PoplarResponse.SerializeToString,
      ),
      'ResetSample': grpc.unary_unary_rpc_method_handler(
          servicer.ResetSample,
          request_deserializer=poplar__pb2.PoplarID.FromString,
          response_serializer=poplar__pb2.PoplarResponse.SerializeToString,
      ),
      'FlushSample': grpc.unary_unary_rpc_method_handler(
          servicer.FlushSample,
          request_deserializer=poplar__pb2.PoplarID.FromString,
          response_serializer=poplar__pb2.PoplarResponse.SerializeToString,
      ),
      'Add': grpc.unary_unary_rpc_method_handler(
          servicer.Add,
          request_deserializer=metrics__pb2.IntervalSummary.FromString,
          response_serializer=poplar__pb2.PoplarResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'poplar.PoplarMetricsCollector', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
