# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: poplar.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='poplar.proto',
  package='poplar',
  syntax='proto3',
  serialized_options=_b('Z\010internal'),
  serialized_pb=_b('\n\x0cpoplar.proto\x12\x06poplar\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\x18\n\x08PoplarID\x12\x0c\n\x04name\x18\x01 \x01(\t\"\xc7\x02\n\rCreateOptions\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x11\n\tchunkSize\x18\x03 \x01(\x05\x12\x11\n\tstreaming\x18\x04 \x01(\x08\x12\x0f\n\x07\x64ynamic\x18\x05 \x01(\x08\x12\x34\n\x08recorder\x18\x06 \x01(\x0e\x32\".poplar.CreateOptions.RecorderType\"\xac\x01\n\x0cRecorderType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x08\n\x04PERF\x10\x01\x12\x0f\n\x0bPERF_SINGLE\x10\x02\x12\x0e\n\nPERF_100MS\x10\x03\x12\x0b\n\x07PERF_1S\x10\x04\x12\x14\n\x10HISTOGRAM_SINGLE\x10\x06\x12\x13\n\x0fHISTOGRAM_100MS\x10\x07\x12\x10\n\x0cHISTOGRAM_1S\x10\x08\x12\x1a\n\x16INTERVAL_SUMMARIZATION\x10\t\".\n\x0ePoplarResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\x08\x42\nZ\x08internalb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,google_dot_protobuf_dot_duration__pb2.DESCRIPTOR,])



_CREATEOPTIONS_RECORDERTYPE = _descriptor.EnumDescriptor(
  name='RecorderType',
  full_name='poplar.CreateOptions.RecorderType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PERF', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PERF_SINGLE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PERF_100MS', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PERF_1S', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HISTOGRAM_SINGLE', index=5, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HISTOGRAM_100MS', index=6, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HISTOGRAM_1S', index=7, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INTERVAL_SUMMARIZATION', index=8, number=9,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=271,
  serialized_end=443,
)
_sym_db.RegisterEnumDescriptor(_CREATEOPTIONS_RECORDERTYPE)


_POPLARID = _descriptor.Descriptor(
  name='PoplarID',
  full_name='poplar.PoplarID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='poplar.PoplarID.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=113,
)


_CREATEOPTIONS = _descriptor.Descriptor(
  name='CreateOptions',
  full_name='poplar.CreateOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='poplar.CreateOptions.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='path', full_name='poplar.CreateOptions.path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chunkSize', full_name='poplar.CreateOptions.chunkSize', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='streaming', full_name='poplar.CreateOptions.streaming', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dynamic', full_name='poplar.CreateOptions.dynamic', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='recorder', full_name='poplar.CreateOptions.recorder', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CREATEOPTIONS_RECORDERTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=443,
)


_POPLARRESPONSE = _descriptor.Descriptor(
  name='PoplarResponse',
  full_name='poplar.PoplarResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='poplar.PoplarResponse.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='poplar.PoplarResponse.status', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=445,
  serialized_end=491,
)

_CREATEOPTIONS.fields_by_name['recorder'].enum_type = _CREATEOPTIONS_RECORDERTYPE
_CREATEOPTIONS_RECORDERTYPE.containing_type = _CREATEOPTIONS
DESCRIPTOR.message_types_by_name['PoplarID'] = _POPLARID
DESCRIPTOR.message_types_by_name['CreateOptions'] = _CREATEOPTIONS
DESCRIPTOR.message_types_by_name['PoplarResponse'] = _POPLARRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PoplarID = _reflection.GeneratedProtocolMessageType('PoplarID', (_message.Message,), {
  'DESCRIPTOR' : _POPLARID,
  '__module__' : 'poplar_pb2'
  # @@protoc_insertion_point(class_scope:poplar.PoplarID)
  })
_sym_db.RegisterMessage(PoplarID)

CreateOptions = _reflection.GeneratedProtocolMessageType('CreateOptions', (_message.Message,), {
  'DESCRIPTOR' : _CREATEOPTIONS,
  '__module__' : 'poplar_pb2'
  # @@protoc_insertion_point(class_scope:poplar.CreateOptions)
  })
_sym_db.RegisterMessage(CreateOptions)

PoplarResponse = _reflection.GeneratedProtocolMessageType('PoplarResponse', (_message.Message,), {
  'DESCRIPTOR' : _POPLARRESPONSE,
  '__module__' : 'poplar_pb2'
  # @@protoc_insertion_point(class_scope:poplar.PoplarResponse)
  })
_sym_db.RegisterMessage(PoplarResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
