# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recorder.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import poplar_pb2 as poplar__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='recorder.proto',
  package='poplar',
  syntax='proto3',
  serialized_options=_b('Z\010internal'),
  serialized_pb=_b('\n\x0erecorder.proto\x12\x06poplar\x1a\x0cpoplar.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"G\n\rEventSendTime\x12\x0c\n\x04name\x18\x01 \x01(\t\x12(\n\x04time\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"+\n\x0c\x45ventSendInt\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x03\",\n\rEventSendBool\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x08\"N\n\x11\x45ventSendDuration\x12\x0c\n\x04name\x18\x01 \x01(\t\x12+\n\x08\x64uration\x18\x02 \x01(\x0b\x32\x19.google.protobuf.Duration2\xd8\x07\n\x15PoplarMetricsRecorder\x12?\n\x0e\x43reateRecorder\x12\x15.poplar.CreateOptions\x1a\x16.poplar.PoplarResponse\x12\x39\n\rCloseRecorder\x12\x10.poplar.PoplarID\x1a\x16.poplar.PoplarResponse\x12\x36\n\nBeginEvent\x12\x10.poplar.PoplarID\x1a\x16.poplar.PoplarResponse\x12\x36\n\nResetEvent\x12\x10.poplar.PoplarID\x1a\x16.poplar.PoplarResponse\x12=\n\x08\x45ndEvent\x12\x19.poplar.EventSendDuration\x1a\x16.poplar.PoplarResponse\x12\x35\n\x05SetID\x12\x14.poplar.EventSendInt\x1a\x16.poplar.PoplarResponse\x12\x38\n\x07SetTime\x12\x15.poplar.EventSendTime\x1a\x16.poplar.PoplarResponse\x12@\n\x0bSetDuration\x12\x19.poplar.EventSendDuration\x1a\x16.poplar.PoplarResponse\x12\x45\n\x10SetTotalDuration\x12\x19.poplar.EventSendDuration\x1a\x16.poplar.PoplarResponse\x12\x38\n\x08SetState\x12\x14.poplar.EventSendInt\x1a\x16.poplar.PoplarResponse\x12:\n\nSetWorkers\x12\x14.poplar.EventSendInt\x1a\x16.poplar.PoplarResponse\x12:\n\tSetFailed\x12\x15.poplar.EventSendBool\x1a\x16.poplar.PoplarResponse\x12\x36\n\x06IncOps\x12\x14.poplar.EventSendInt\x1a\x16.poplar.PoplarResponse\x12\x37\n\x07IncSize\x12\x14.poplar.EventSendInt\x1a\x16.poplar.PoplarResponse\x12\x38\n\x08IncError\x12\x14.poplar.EventSendInt\x1a\x16.poplar.PoplarResponse\x12=\n\rIncIterations\x12\x14.poplar.EventSendInt\x1a\x16.poplar.PoplarResponseB\nZ\x08internalb\x06proto3')
  ,
  dependencies=[poplar__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,google_dot_protobuf_dot_duration__pb2.DESCRIPTOR,])




_EVENTSENDTIME = _descriptor.Descriptor(
  name='EventSendTime',
  full_name='poplar.EventSendTime',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='poplar.EventSendTime.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='poplar.EventSendTime.time', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=176,
)


_EVENTSENDINT = _descriptor.Descriptor(
  name='EventSendInt',
  full_name='poplar.EventSendInt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='poplar.EventSendInt.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='poplar.EventSendInt.value', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=178,
  serialized_end=221,
)


_EVENTSENDBOOL = _descriptor.Descriptor(
  name='EventSendBool',
  full_name='poplar.EventSendBool',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='poplar.EventSendBool.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='poplar.EventSendBool.value', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=223,
  serialized_end=267,
)


_EVENTSENDDURATION = _descriptor.Descriptor(
  name='EventSendDuration',
  full_name='poplar.EventSendDuration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='poplar.EventSendDuration.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='duration', full_name='poplar.EventSendDuration.duration', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=269,
  serialized_end=347,
)

_EVENTSENDTIME.fields_by_name['time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_EVENTSENDDURATION.fields_by_name['duration'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
DESCRIPTOR.message_types_by_name['EventSendTime'] = _EVENTSENDTIME
DESCRIPTOR.message_types_by_name['EventSendInt'] = _EVENTSENDINT
DESCRIPTOR.message_types_by_name['EventSendBool'] = _EVENTSENDBOOL
DESCRIPTOR.message_types_by_name['EventSendDuration'] = _EVENTSENDDURATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EventSendTime = _reflection.GeneratedProtocolMessageType('EventSendTime', (_message.Message,), {
  'DESCRIPTOR' : _EVENTSENDTIME,
  '__module__' : 'recorder_pb2'
  # @@protoc_insertion_point(class_scope:poplar.EventSendTime)
  })
_sym_db.RegisterMessage(EventSendTime)

EventSendInt = _reflection.GeneratedProtocolMessageType('EventSendInt', (_message.Message,), {
  'DESCRIPTOR' : _EVENTSENDINT,
  '__module__' : 'recorder_pb2'
  # @@protoc_insertion_point(class_scope:poplar.EventSendInt)
  })
_sym_db.RegisterMessage(EventSendInt)

EventSendBool = _reflection.GeneratedProtocolMessageType('EventSendBool', (_message.Message,), {
  'DESCRIPTOR' : _EVENTSENDBOOL,
  '__module__' : 'recorder_pb2'
  # @@protoc_insertion_point(class_scope:poplar.EventSendBool)
  })
_sym_db.RegisterMessage(EventSendBool)

EventSendDuration = _reflection.GeneratedProtocolMessageType('EventSendDuration', (_message.Message,), {
  'DESCRIPTOR' : _EVENTSENDDURATION,
  '__module__' : 'recorder_pb2'
  # @@protoc_insertion_point(class_scope:poplar.EventSendDuration)
  })
_sym_db.RegisterMessage(EventSendDuration)


DESCRIPTOR._options = None

_POPLARMETRICSRECORDER = _descriptor.ServiceDescriptor(
  name='PoplarMetricsRecorder',
  full_name='poplar.PoplarMetricsRecorder',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=350,
  serialized_end=1334,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateRecorder',
    full_name='poplar.PoplarMetricsRecorder.CreateRecorder',
    index=0,
    containing_service=None,
    input_type=poplar__pb2._CREATEOPTIONS,
    output_type=poplar__pb2._POPLARRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CloseRecorder',
    full_name='poplar.PoplarMetricsRecorder.CloseRecorder',
    index=1,
    containing_service=None,
    input_type=poplar__pb2._POPLARID,
    output_type=poplar__pb2._POPLARRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='BeginEvent',
    full_name='poplar.PoplarMetricsRecorder.BeginEvent',
    index=2,
    containing_service=None,
    input_type=poplar__pb2._POPLARID,
    output_type=poplar__pb2._POPLARRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ResetEvent',
    full_name='poplar.PoplarMetricsRecorder.ResetEvent',
    index=3,
    containing_service=None,
    input_type=poplar__pb2._POPLARID,
    output_type=poplar__pb2._POPLARRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='EndEvent',
    full_name='poplar.PoplarMetricsRecorder.EndEvent',
    index=4,
    containing_service=None,
    input_type=_EVENTSENDDURATION,
    output_type=poplar__pb2._POPLARRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetID',
    full_name='poplar.PoplarMetricsRecorder.SetID',
    index=5,
    containing_service=None,
    input_type=_EVENTSENDINT,
    output_type=poplar__pb2._POPLARRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetTime',
    full_name='poplar.PoplarMetricsRecorder.SetTime',
    index=6,
    containing_service=None,
    input_type=_EVENTSENDTIME,
    output_type=poplar__pb2._POPLARRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetDuration',
    full_name='poplar.PoplarMetricsRecorder.SetDuration',
    index=7,
    containing_service=None,
    input_type=_EVENTSENDDURATION,
    output_type=poplar__pb2._POPLARRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetTotalDuration',
    full_name='poplar.PoplarMetricsRecorder.SetTotalDuration',
    index=8,
    containing_service=None,
    input_type=_EVENTSENDDURATION,
    output_type=poplar__pb2._POPLARRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetState',
    full_name='poplar.PoplarMetricsRecorder.SetState',
    index=9,
    containing_service=None,
    input_type=_EVENTSENDINT,
    output_type=poplar__pb2._POPLARRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetWorkers',
    full_name='poplar.PoplarMetricsRecorder.SetWorkers',
    index=10,
    containing_service=None,
    input_type=_EVENTSENDINT,
    output_type=poplar__pb2._POPLARRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetFailed',
    full_name='poplar.PoplarMetricsRecorder.SetFailed',
    index=11,
    containing_service=None,
    input_type=_EVENTSENDBOOL,
    output_type=poplar__pb2._POPLARRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='IncOps',
    full_name='poplar.PoplarMetricsRecorder.IncOps',
    index=12,
    containing_service=None,
    input_type=_EVENTSENDINT,
    output_type=poplar__pb2._POPLARRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='IncSize',
    full_name='poplar.PoplarMetricsRecorder.IncSize',
    index=13,
    containing_service=None,
    input_type=_EVENTSENDINT,
    output_type=poplar__pb2._POPLARRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='IncError',
    full_name='poplar.PoplarMetricsRecorder.IncError',
    index=14,
    containing_service=None,
    input_type=_EVENTSENDINT,
    output_type=poplar__pb2._POPLARRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='IncIterations',
    full_name='poplar.PoplarMetricsRecorder.IncIterations',
    index=15,
    containing_service=None,
    input_type=_EVENTSENDINT,
    output_type=poplar__pb2._POPLARRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_POPLARMETRICSRECORDER)

DESCRIPTOR.services_by_name['PoplarMetricsRecorder'] = _POPLARMETRICSRECORDER

# @@protoc_insertion_point(module_scope)
