# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import poplar_pb2 as poplar__pb2
from . import recorder_pb2 as recorder__pb2


class PoplarMetricsRecorderStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateRecorder = channel.unary_unary(
        '/poplar.PoplarMetricsRecorder/CreateRecorder',
        request_serializer=poplar__pb2.CreateOptions.SerializeToString,
        response_deserializer=poplar__pb2.PoplarResponse.FromString,
        )
    self.CloseRecorder = channel.unary_unary(
        '/poplar.PoplarMetricsRecorder/CloseRecorder',
        request_serializer=poplar__pb2.PoplarID.SerializeToString,
        response_deserializer=poplar__pb2.PoplarResponse.FromString,
        )
    self.BeginEvent = channel.unary_unary(
        '/poplar.PoplarMetricsRecorder/BeginEvent',
        request_serializer=poplar__pb2.PoplarID.SerializeToString,
        response_deserializer=poplar__pb2.PoplarResponse.FromString,
        )
    self.ResetEvent = channel.unary_unary(
        '/poplar.PoplarMetricsRecorder/ResetEvent',
        request_serializer=poplar__pb2.PoplarID.SerializeToString,
        response_deserializer=poplar__pb2.PoplarResponse.FromString,
        )
    self.EndEvent = channel.unary_unary(
        '/poplar.PoplarMetricsRecorder/EndEvent',
        request_serializer=recorder__pb2.EventSendDuration.SerializeToString,
        response_deserializer=poplar__pb2.PoplarResponse.FromString,
        )
    self.SetID = channel.unary_unary(
        '/poplar.PoplarMetricsRecorder/SetID',
        request_serializer=recorder__pb2.EventSendInt.SerializeToString,
        response_deserializer=poplar__pb2.PoplarResponse.FromString,
        )
    self.SetTime = channel.unary_unary(
        '/poplar.PoplarMetricsRecorder/SetTime',
        request_serializer=recorder__pb2.EventSendTime.SerializeToString,
        response_deserializer=poplar__pb2.PoplarResponse.FromString,
        )
    self.SetDuration = channel.unary_unary(
        '/poplar.PoplarMetricsRecorder/SetDuration',
        request_serializer=recorder__pb2.EventSendDuration.SerializeToString,
        response_deserializer=poplar__pb2.PoplarResponse.FromString,
        )
    self.SetTotalDuration = channel.unary_unary(
        '/poplar.PoplarMetricsRecorder/SetTotalDuration',
        request_serializer=recorder__pb2.EventSendDuration.SerializeToString,
        response_deserializer=poplar__pb2.PoplarResponse.FromString,
        )
    self.SetState = channel.unary_unary(
        '/poplar.PoplarMetricsRecorder/SetState',
        request_serializer=recorder__pb2.EventSendInt.SerializeToString,
        response_deserializer=poplar__pb2.PoplarResponse.FromString,
        )
    self.SetWorkers = channel.unary_unary(
        '/poplar.PoplarMetricsRecorder/SetWorkers',
        request_serializer=recorder__pb2.EventSendInt.SerializeToString,
        response_deserializer=poplar__pb2.PoplarResponse.FromString,
        )
    self.SetFailed = channel.unary_unary(
        '/poplar.PoplarMetricsRecorder/SetFailed',
        request_serializer=recorder__pb2.EventSendBool.SerializeToString,
        response_deserializer=poplar__pb2.PoplarResponse.FromString,
        )
    self.IncOps = channel.unary_unary(
        '/poplar.PoplarMetricsRecorder/IncOps',
        request_serializer=recorder__pb2.EventSendInt.SerializeToString,
        response_deserializer=poplar__pb2.PoplarResponse.FromString,
        )
    self.IncSize = channel.unary_unary(
        '/poplar.PoplarMetricsRecorder/IncSize',
        request_serializer=recorder__pb2.EventSendInt.SerializeToString,
        response_deserializer=poplar__pb2.PoplarResponse.FromString,
        )
    self.IncError = channel.unary_unary(
        '/poplar.PoplarMetricsRecorder/IncError',
        request_serializer=recorder__pb2.EventSendInt.SerializeToString,
        response_deserializer=poplar__pb2.PoplarResponse.FromString,
        )
    self.IncIterations = channel.unary_unary(
        '/poplar.PoplarMetricsRecorder/IncIterations',
        request_serializer=recorder__pb2.EventSendInt.SerializeToString,
        response_deserializer=poplar__pb2.PoplarResponse.FromString,
        )


class PoplarMetricsRecorderServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateRecorder(self, request, context):
    """Create builds a new recorder instance which creates a local file,
    while the close recorder method flushes the contents of that
    recorder and closes the file.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CloseRecorder(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BeginEvent(self, request, context):
    """Event Lifecycle methods
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ResetEvent(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EndEvent(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetID(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetTime(self, request, context):
    """Timers
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetDuration(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetTotalDuration(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetState(self, request, context):
    """Guages
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetWorkers(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetFailed(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def IncOps(self, request, context):
    """Counters
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def IncSize(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def IncError(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def IncIterations(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PoplarMetricsRecorderServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateRecorder': grpc.unary_unary_rpc_method_handler(
          servicer.CreateRecorder,
          request_deserializer=poplar__pb2.CreateOptions.FromString,
          response_serializer=poplar__pb2.PoplarResponse.SerializeToString,
      ),
      'CloseRecorder': grpc.unary_unary_rpc_method_handler(
          servicer.CloseRecorder,
          request_deserializer=poplar__pb2.PoplarID.FromString,
          response_serializer=poplar__pb2.PoplarResponse.SerializeToString,
      ),
      'BeginEvent': grpc.unary_unary_rpc_method_handler(
          servicer.BeginEvent,
          request_deserializer=poplar__pb2.PoplarID.FromString,
          response_serializer=poplar__pb2.PoplarResponse.SerializeToString,
      ),
      'ResetEvent': grpc.unary_unary_rpc_method_handler(
          servicer.ResetEvent,
          request_deserializer=poplar__pb2.PoplarID.FromString,
          response_serializer=poplar__pb2.PoplarResponse.SerializeToString,
      ),
      'EndEvent': grpc.unary_unary_rpc_method_handler(
          servicer.EndEvent,
          request_deserializer=recorder__pb2.EventSendDuration.FromString,
          response_serializer=poplar__pb2.PoplarResponse.SerializeToString,
      ),
      'SetID': grpc.unary_unary_rpc_method_handler(
          servicer.SetID,
          request_deserializer=recorder__pb2.EventSendInt.FromString,
          response_serializer=poplar__pb2.PoplarResponse.SerializeToString,
      ),
      'SetTime': grpc.unary_unary_rpc_method_handler(
          servicer.SetTime,
          request_deserializer=recorder__pb2.EventSendTime.FromString,
          response_serializer=poplar__pb2.PoplarResponse.SerializeToString,
      ),
      'SetDuration': grpc.unary_unary_rpc_method_handler(
          servicer.SetDuration,
          request_deserializer=recorder__pb2.EventSendDuration.FromString,
          response_serializer=poplar__pb2.PoplarResponse.SerializeToString,
      ),
      'SetTotalDuration': grpc.unary_unary_rpc_method_handler(
          servicer.SetTotalDuration,
          request_deserializer=recorder__pb2.EventSendDuration.FromString,
          response_serializer=poplar__pb2.PoplarResponse.SerializeToString,
      ),
      'SetState': grpc.unary_unary_rpc_method_handler(
          servicer.SetState,
          request_deserializer=recorder__pb2.EventSendInt.FromString,
          response_serializer=poplar__pb2.PoplarResponse.SerializeToString,
      ),
      'SetWorkers': grpc.unary_unary_rpc_method_handler(
          servicer.SetWorkers,
          request_deserializer=recorder__pb2.EventSendInt.FromString,
          response_serializer=poplar__pb2.PoplarResponse.SerializeToString,
      ),
      'SetFailed': grpc.unary_unary_rpc_method_handler(
          servicer.SetFailed,
          request_deserializer=recorder__pb2.EventSendBool.FromString,
          response_serializer=poplar__pb2.PoplarResponse.SerializeToString,
      ),
      'IncOps': grpc.unary_unary_rpc_method_handler(
          servicer.IncOps,
          request_deserializer=recorder__pb2.EventSendInt.FromString,
          response_serializer=poplar__pb2.PoplarResponse.SerializeToString,
      ),
      'IncSize': grpc.unary_unary_rpc_method_handler(
          servicer.IncSize,
          request_deserializer=recorder__pb2.EventSendInt.FromString,
          response_serializer=poplar__pb2.PoplarResponse.SerializeToString,
      ),
      'IncError': grpc.unary_unary_rpc_method_handler(
          servicer.IncError,
          request_deserializer=recorder__pb2.EventSendInt.FromString,
          response_serializer=poplar__pb2.PoplarResponse.SerializeToString,
      ),
      'IncIterations': grpc.unary_unary_rpc_method_handler(
          servicer.IncIterations,
          request_deserializer=recorder__pb2.EventSendInt.FromString,
          response_serializer=poplar__pb2.PoplarResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'poplar.PoplarMetricsRecorder', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
